### ISSUE TITLE
Is this extension really needed?

### ISSUE THREAD

**Issue by mediaessenz** [Gernott/wp_mailqueue#1]
Both TYPO3 Versions covered by this extension using the Synfony-Mailer, which already brings spooler/queue sending.

It can be activated by setting this TYPO3 global to 'file' or 'memory':
```php
$GLOBALS['TYPO3_CONF_VARS']['MAIL']['transport_spool_type']
```
If 'file' is used, a second value has to be set, which detemines where the interim files (serialized mail object) of the sending queue should be stored:
```php
$GLOBALS['TYPO3_CONF_VARS']['MAIL']['transport_spool_filepath']
```

The final sending is done by the SendEmailCommand, which also come with the TYPO3 core. It can easily added as scheduler task and allows to set, how many mails should be send per cycle.

So, what is the different/advantage of this extension?

**Comment by Gernott** [comment]
Thank you for this. I didn't know it. Great!

The main differences are:
- that you can choose regular sending or queue sending at each (PHP)call by using the core method or our extension method.
- there is a backend module,where you can delete mails from the queue and you have a log.
