### ISSUE TITLE
wp_MailQueue

### ISSUE THREAD

**Issue by aiturria-spain** [Gernott/wp_mailqueue#5]
Hi Gernott

I'm looking for such an extension to send mails throw a mailqueue. It seems to be that your extension does the work for me. I'm just wondering what's the difference between the fields $body and $bodyHtml.

I want to send rendered mail templates (with StandaloneView) throw your mailqueue. How do I have to fill fields and which ones in my case?

Thanks for your help..

Kind regards

Alberto

**Comment by Gernott** [comment]
Hi Alberto,
$body is for plain text, $bodyHtml for HTML Mails.
Gernot
